version: '3.8'

services:
  web:
    build: .
    container_name: django_menu_web
    command: python manage.py runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env